name: GitHub - WordCloud - Readme

# everday at 00:00 UTC.
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme with WordCloud
    runs-on: ubuntu-latest
    steps:
      - uses: Parply/profile-wordcloud@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}